// SPDX-License-Identifier: GPL-2.0

#include <dm.h>
#include <asm/io.h>
#include <dt-bindings/clock/mediatek,mt6789-clk.h>
#include "clk-mtk.h"

#define MT6789_PLL_FMAX		(3800UL * MHZ)
#define MT6789_PLL_FMIN		(1500UL * MHZ)
#define MT6789_INTEGER_BITS	8
#define PLL_AO			BIT(1)

/* apmixedsys */
#define PLL(_id, _reg, _en_reg, _en_mask, _pll_en_bit,	\
			_pwr_reg, _flags, _rst_bar_mask,		\
			_pd_reg, _pd_shift, _tuner_reg,			\
			_tuner_en_reg, _tuner_en_bit,			\
			_pcw_reg, _pcw_shift, _pcwbits) {		\
		.id = _id,						\
		.reg = _reg,						\
		.en_reg = _en_reg,					\
		.en_mask = _en_mask,					\
		.pll_en_bit = _pll_en_bit,				\
		.pwr_reg = _pwr_reg,					\
		.flags = _flags,					\
		.rst_bar_mask = _rst_bar_mask,				\
		.fmax = MT6789_PLL_FMAX,				\
		.fmin = MT6789_PLL_FMIN,				\
		.pd_reg = _pd_reg,					\
		.pd_shift = _pd_shift,					\
		.tuner_reg = _tuner_reg,				\
		.tuner_en_reg = _tuner_en_reg,				\
		.tuner_en_bit = _tuner_en_bit,				\
		.pcw_reg = _pcw_reg,					\
		.pcw_shift = _pcw_shift,				\
		.pcwbits = _pcwbits,					\
		.pcwibits = MT6789_INTEGER_BITS,			\
	}

static const struct mtk_pll_data apmixed_plls[] = {
	PLL(CLK_APMIXED_ARMPLL_LL, 0x208, 0x208, 0, 0, 0x214, PLL_AO, BIT(0), 0x20C, 24, 0, 0, 0 , 0x20C, 0, 22),
	PLL(CLK_APMIXED_ARMPLL_BL0, 0x218, 0x218, 0, 0, 0x224, PLL_AO, BIT(0), 0x21C, 24, 0, 0, 0 , 0x21C, 0, 22),
	PLL(CLK_APMIXED_CCIPLL, 0x258, 0x258, 0, 0, 0x264, PLL_AO, BIT(0), 0x25C, 24, 0, 0, 0, 0x25C, 0, 22),
	PLL(CLK_APMIXED_MPLL, 0x390, 0x390, 0, 0, 0x39C, PLL_AO, BIT(0), 0x394, 24, 0, 0, 0, 0x394, 0, 22),
	PLL(CLK_APMIXED_MAINPLL, 0x340, 0x340, 0xff000000, 0, 0x34C, HAVE_RST_BAR | PLL_AO, BIT(23), 0x344, 24, 0, 0, 0, 0x344, 0, 22),
	PLL(CLK_APMIXED_UNIVPLL, 0x308, 0x308, 0xff000000, 0, 0x314, HAVE_RST_BAR, BIT(23), 0x30C, 24, 0, 0, 0 , 0x30C, 0, 22),
	PLL(CLK_APMIXED_MSDCPLL, 0x350, 0x350, 0, 0, 0x35C, 0, BIT(0), 0x354, 24, 0, 0, 0, 0x354, 0, 22),
	PLL(CLK_APMIXED_MMPLL, 0x360, 0x360, 0xff000000, 0, 0x36C, HAVE_RST_BAR, BIT(23) , 0x364, 24, 0, 0, 0 , 0x364, 0, 22),
	PLL(CLK_APMIXED_NPUPLL, 0x3B4, 0x3B4, 0xff000000, 0, 0x3C0, 0, BIT(0), 0x3B8, 24, 0, 0, 0, 0x3B8, 0, 22),
	PLL(CLK_APMIXED_MFGPLL, 0x268, 0x268, 0, 0, 0x274, 0, BIT(0), 0x26C, 24, 0, 0, 0, 0x26C, 0, 22),
	PLL(CLK_APMIXED_TVDPLL, 0x380  0x380, 0, 0, 0x38C , 0, BIT(0), 0x384, 24, 0, 0, 0, 0x384, 0, 22),
	PLL(CLK_APMIXED_APLL1, 0x318,  0x318, 0, 0, 0x328, 0, BIT(0), 0x31C, 24, 0x040, 0x00C, 0, 0x320, 0, 32),
	PLL(CLK_APMIXED_APLL2, 0x32C, 0x32C, 0, 0, 0x33C, 0, BIT(0), 0x330, 24, 0x044, 0x00C, 5, 0x334, 0, 32),
	PLL(CLK_APMIXED_USBPLL, 0x3C4, 0x3CC, 0, 2, 0x3CC, HAVE_RST_BAR, BIT(23), 0x3C4, 24, 0, 0, 0, 0x3C4, 0, 22),
};

static const struct mtk_fixed_clk top_fixed_clks[] = {
	FIXED_CLK(CLK_TOP_CLK32K, CLK_XTAL, 32000),
	FIXED_CLK(CLK_TOP_CLK26M, CLK_XTAL, 26000000),
	FIXED_CLK(CLK_TOP_ULPOSC, CLK_XTAL, 260000000),
};

static const struct mtk_fixed_factor top_fixed_divs[] = {
	FACTOR(CLK_TOP_CLKRTC, CLK_TOP_CLK32K, 1, 1, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_CLK13M, CLK_TOP_CLK26M, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_F26M_CK_D2, CLK_TOP_CLK26M, 1, 2, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_MFGPLL_CK, CLK_APMIXED_MFGPLL, 1, 1, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_SYSPLL_D4, CLK_APMIXED_MAINPLL, 1, 4, CLK_PARENT_APMIXED),

	FACTOR(CLK_TOP_MAINPLL_D4_D2, CLK_TOP_MAINPLL_D4, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D4_D4, CLK_TOP_MAINPLL_D4, 1, 16, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D4_D8, CLK_TOP_MAINPLL_D4, 1, 32, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D4_D16, CLK_TOP_MAINPLL_D4, 1, 64, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_MAINPLL_D5, CLK_APMIXED_MAINPLL, 1, 5, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MAINPLL_D5_D2, CLK_TOP_MAINPLL_D5, 1, 10, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D5_D4, CLK_TOP_MAINPLL_D5, 1, 20, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D5_D8, CLK_TOP_MAINPLL_D5, 1, 40, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_MAINPLL_D6, CLK_APMIXED_MAINPLL, 1, 6, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MAINPLL_D6_D2, CLK_TOP_MAINPLL_D6, 1, 12, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D6_D4, CLK_TOP_MAINPLL_D6, 1, 24, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_MAINPLL_D7, CLK_APMIXED_MAINPLL, 1, 7, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MAINPLL_D7_D2, CLK_TOP_MAINPLL_D7, 1, 14, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D7_D4, CLK_TOP_MAINPLL_D7, 1, 28, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D7_D8, CLK_TOP_MAINPLL_D7, 1, 56, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_MAINPLL_D9, CLK_APMIXED_MAINPLL, 1, 9, CLK_PARENT_APMIXED),

	FACTOR(CLK_TOP_UNIVPLL_D4, CLK_TOP_UNIVPLL, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D4_D2, CLK_TOP_UNIVPLL_D4, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D4_D4, CLK_TOP_UNIVPLL_D4, 1, 16, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D4_D8, CLK_TOP_UNIVPLL_D4, 1, 32, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_UNIVPLL_D5, CLK_TOP_UNIVPLL, 1, 5, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D5_D2, CLK_TOP_UNIVPLL_D5, 1, 10, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D5_D4, CLK_TOP_UNIVPLL_D5, 1, 20, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_UNIVPLL_D6, CLK_TOP_UNIVPLL, 1, 6, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D6_D2, CLK_TOP_UNIVPLL_D6, 1, 12, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D6_D4, CLK_TOP_UNIVPLL_D6, 1, 24, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D6_D8, CLK_TOP_UNIVPLL_D6, 1, 48, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D6_D16, CLK_TOP_UNIVPLL_D6, 1, 96, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_UNIVPLL_D7, CLK_TOP_UNIVPLL, 1, 7, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D7_D2, CLK_TOP_UNIVPLL_D7, 1, 26, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D7_D4, CLK_TOP_UNIVPLL_D7, 1, 52, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D7_D8, CLK_TOP_UNIVPLL_D7, 1, 104, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D7_D16, CLK_TOP_UNIVPLL_D7, 1, 208, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D7_D32, CLK_TOP_UNIVPLL_D7, 1, 416, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_APLL1_CK, CLK_APMIXED_APLL1, 1, 1, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL1_D2, CLK_APMIXED_APLL1, 1, 2, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL1_D4, CLK_APMIXED_APLL1, 1, 4, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL1_D8, CLK_APMIXED_APLL1, 1, 8, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL2_CK, CLK_APMIXED_APLL2, 1, 1, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL2_D2, CLK_APMIXED_APLL2, 1, 2, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL2_D4, CLK_APMIXED_APLL2, 1, 4, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL2_D8, CLK_APMIXED_APLL2, 1, 8, CLK_PARENT_APMIXED),

	FACTOR(CLK_TOP_MMPLL_D4, CLK_APMIXED_MMPLL, 1, 4, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MMPLL_D4_D2, CLK_TOP_MMPLL_D4, 1, 8, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_MMPLL_D5, CLK_APMIXED_MMPLL, 1, 5, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MMPLL_D5_D2, CLK_TOP_MMPLL_D5, 1, 12, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_MMPLL_D6, CLK_APMIXED_MMPLL, 1, 5, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MMPLL_D6_D2, CLK_TOP_MMPLL_D6, 1, 12, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_MMPLL_D7, CLK_APMIXED_MMPLL, 1, 7, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MMPLL_D9, CLK_APMIXED_MMPLL, 1, 9, CLK_PARENT_APMIXED),

	FACTOR(CLK_TOP_MSDCPLL_CK, CLK_APMIXED_MSDCPLL, 1, 1, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MSDCPLL_D2, CLK_APMIXED_MSDCPLL, 1, 2, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MSDCPLL_D4, CLK_APMIXED_MSDCPLL, 1, 4, CLK_PARENT_APMIXED),

	FACTOR(CLK_TOP_NPUPLL_CK, CLK_APMIXED_NPUPLL, 1, 1, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_TVDPLL_CK, CLK_APMIXED_TVDPLL, 1, 1, CLK_PARENT_APMIXED),

	FACTOR(CLK_TOP_OSC_D2, CLK_TOP_ULPOSC, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_OSC_D4, CLK_TOP_ULPOSC, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_OSC_D8, CLK_TOP_ULPOSC, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_OSC_D10, CLK_TOP_ULPOSC, 1, 10, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_OSC_D16, CLK_TOP_ULPOSC, 1, 16, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_OSC_D20, CLK_TOP_ULPOSC, 1, 20, CLK_PARENT_TOPCKGEN),
};

static const int axi_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D4,
	CLK_TOP_MAINPLL_D7_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_OSC_D4
};

static const int spm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_OSC_D10,
	CLK_TOP_MAINPLL_D7_D4,
	CLK_TOP_CLKRTC
};

static const int scp_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D4,
	CLK_TOP_NPUPLL_CK,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_MAINPLL_D7
};

static const int bus_aximem_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D7_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MAINPLL_D6
};

static const int disp_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D6_D2,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MMPLL_D6_D2,
	CLK_TOP_UNIVPLL_D5_D2,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_MMPLL_D7,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_MMPLL_D5_D2
};

static const int mdp_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MMPLL_D6_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MMPLL_D4_D2,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_MAINPLL_D5,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_TVDPLL_CK,
	CLK_TOP_UNIVPLL_D4,
	CLK_TOP_MMPLL_D5_D2
};

static const int img1_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D4,
	CLK_TOP_TVDPLL_CK,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MAINPLL_D6
	CLK_TOP_MMPLL_D4_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MMPLL_D6_D2,
	CLK_TOP_MMPLL_D5_D2
};

static const int ipe_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MMPLL_D6_D2,
	CLK_TOP_MMPLL_D5_D2
};

static const int cam_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D4,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MMPLL_D7,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_NPUPLL_CK
};

static const int mfg_ref_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_MAINPLL_D5_D2
};

static const int mfg_pll_parents[] = {
	CLK_TOP_MFG_REF_SEL,
	CLK_TOP_MFGPLL_CK
};

/*
static const int camtg_parents[] = {
	CLK_TOP_CLK26M,
	"univpll_192m_d8",
	CLK_TOP_UNIVPLL_D6_D8,
	"univpll_192m_d4",
	"univpll_d6_d16",
	CLK_TOP_F26M_CK_D2,
	"univpll_192m_d16",
	"univpll_192m_d32"
};

static const int camtg2_parents[] = {
	CLK_TOP_CLK26M,
	"univpll_192m_d8",
	CLK_TOP_UNIVPLL_D6_D8,
	"univpll_192m_d4",
	"univpll_d6_d16",
	CLK_TOP_F26M_CK_D2,
	"univpll_192m_d16",
	"univpll_192m_d32"
};

static const int camtg3_parents[] = {
	CLK_TOP_CLK26M,
	"univpll_192m_d8",
	CLK_TOP_UNIVPLL_D6_D8,
	"univpll_192m_d4",
	"univpll_d6_d16",
	CLK_TOP_F26M_CK_D2,
	"univpll_192m_d16",
	"univpll_192m_d32"
};

static const int camtg4_parents[] = {
	CLK_TOP_CLK26M,
	"univpll_192m_d8",
	CLK_TOP_UNIVPLL_D6_D8,
	"univpll_192m_d4",
	"univpll_d6_d16",
	CLK_TOP_F26M_CK_D2,
	"univpll_192m_d16",
	"univpll_192m_d32"
};

static const int camtg5_parents[] = {
	CLK_TOP_CLK26M,
	"univpll_192m_d8",
	CLK_TOP_UNIVPLL_D6_D8,
	"univpll_192m_d4",
	"univpll_d6_d16",
	CLK_TOP_F26M_CK_D2,
	"univpll_192m_d16",
	"univpll_192m_d32"
};

static const int camtg6_parents[] = {
	CLK_TOP_CLK26M,
	"univpll_192m_d8",
	CLK_TOP_UNIVPLL_D6_D8,
	"univpll_192m_d4",
	"univpll_d6_d16",
	CLK_TOP_F26M_CK_D2,
	"univpll_192m_d16",
	"univpll_192m_d32"
};
*/
static const int uart_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D6_D8
};

static const int spi_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D5_D4,
	CLK_TOP_MAINPLL_D6_D4,
	CLK_TOP_MSDCPLL_D4,
	CLK_TOP_MSDCPLL_D2,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_MAINPLL_D4_D4,
	CLK_TOP_UNIVPLL_D5_D4
};

static const int msdc5hclk_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D6_D2
};

static const int msdc50_0_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MSDCPLL_CK,
	CLK_TOP_MSDCPLL_D2,
	CLK_TOP_UNIVPLL_D2_D4,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_UNIVPLL_D4_D2
};

static const int msdc30_1_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D6_D2,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_MAINPLL_D7_D2,
	CLK_TOP_MSDCPLL_D2
};

static const int audio_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D5_D8,
	CLK_TOP_MAINPLL_D7_D8,
	CLK_TOP_MAINPLL_D4_D16
};

static const int aud_intbus_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D4,
	CLK_TOP_MAINPLL_D7_D4
};

static const int pwrap_ulposc_parents[] = {
	CLK_TOP_OSC_D10,
	CLK_TOP_CLK26M,
	CLK_TOP_OSC_D4,
	CLK_TOP_OSC_D8,
	CLK_TOP_OSC_D16
};

static const int atb_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D5_D2
};

static const int sspm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D7_D2,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MAINPLL_D9,
	CLK_TOP_MAINPLL_D4_D2
};

static const int scam_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D5_D4
};

static const int disp_pwm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D6_D4,
	CLK_TOP_OSC_D2,
	CLK_TOP_OSC_D4,
	CLK_TOP_OSC_D16
};

static const int usb_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D5_D4,
	CLK_TOP_UNIVPLL_D6_D4,
	CLK_TOP_UNIVPLL_D5_D2
};

static const int i2c_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D6,
	CLK_TOP_UNIVPLL_D5_D4
};

static const int seninf_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D4_D4,
	CLK_TOP_UNIVPLL_D6_D2,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_NPUPLL_CK,
	CLK_TOP_MMPLL_D7,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D5
};

static const int seninf1_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D4_D4,
	CLK_TOP_UNIVPLL_D6_D2,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_NPUPLL_CK,
	CLK_TOP_MMPLL_D7,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D5
};

static const int seninf2_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D4_D4,
	CLK_TOP_UNIVPLL_D6_D2,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_NPUPLL_CK,
	CLK_TOP_MMPLL_D7,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D5
};

static const int seninf3_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D4_D4,
	CLK_TOP_UNIVPLL_D6_D2,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_NPUPLL_CK,
	CLK_TOP_MMPLL_D7,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D5
};

static const int dxcc_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D4_D4,
	CLK_TOP_MAINPLL_D4_D6
};

static const int aud_engen1_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_APLL1_D2,
	CLK_TOP_APLL1_D4,
	CLK_TOP_APLL1_D8
};

static const int aud_engen2_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_APLL2_D2,
	CLK_TOP_APLL2_D4,
	CLK_TOP_APLL2_D8
};

static const int aes_ufsfde_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_MAINPLL_D4_D4,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_UNIVPLL_D6
};

static const int ufs_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D4,
	CLK_TOP_MAINPLL_D4_D6,
	CLK_TOP_UNIVPLL_D4_D4,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MSDCPLL_D2
};

static const int aud_1_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_APLL1_CK
};

static const int aud_2_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_APLL2_CK
};

static const int dpmaif_main_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D4_D4,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_UNIVPLL_D4_D2
};

static const int venc_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MMPLL_D7,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_MMPLL_D9,
	CLK_TOP_UNIVPLL_D4_D4,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_UNIVPLL_D4,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_UNIVPLL_D5_D2,
	CLK_TOP_MAINPLL_D5
};

static const int vdec_parents[] = {
	CLK_TOP_CLK26M,
//	"univpll_192m_d2",
	CLK_TOP_UNIVPLL_D5_D4,
	CLK_TOP_MAINPLL_D5,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MMPLL_D6_D2,
	CLK_TOP_UNIVPLL_D5_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_UNIVPLL_D7,
	CLK_TOP_MMPLL_D7,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_UNIVPLL_D4,
	CLK_TOP_UNIVPLL_D6
};

static const int camtm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D7,
	CLK_TOP_UNIVPLL_D6_D2,
	CLK_TOP_UNIVPLL_D4_D2
};

static const int pwm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D4_D8
};

static const int audio_h_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D7,
	CLK_TOP_APLL1_CK,
	CLK_TOP_APLL2_CK
};

static const int spmi_mst_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_F26M_CK_D2,
	CLK_TOP_OSC_D8,
	CLK_TOP_OSC_D10,
	CLK_TOP_OSC_D16,
	CLK_TOP_OSC_D20,
	CLK_TOP_CLKRTC
};

static const int dvfsrc_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_OSC_D10
};

static const int aes_msdcfde_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_MAINPLL_D4_D4,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_UNIVPLL_D6
};

static const int mcupm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D6_D4,
	CLK_TOP_MAINPLL_D6_D2
};

static const int dsi_occ_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_UNIVPLL_D5_D2,
	CLK_TOP_UNIVPLL_D4_D2
};

static const struct mtk_composite top_muxes[] = {
	/* CLK_CFG_0 */
	MUX_GATE(CLK_TOP_AXI_SEL, axi_parents, 0x18, 0, 3, 7),
	MUX_GATE(CLK_TOP_SPM_SEL, spm_parents, 0x18, 8, 2, 15),
	MUX_GATE(CLK_TOP_SCP_SEL, scp_parents, 0x18, 16, 3, 23),
	MUX_GATE(CLK_TOP_BUS_AXIMEM_SEL, bus_aximem_parents, 0x18, 24, 3, 31),
	/* CLK_CFG_1 */
	MUX_GATE(CLK_TOP_DISP_SEL, disp_parents, 0x28, 0, 4, 7),
	MUX_GATE(CLK_TOP_MDP_SEL, mdp_parents, 0x28, 8, 4, 15),
	MUX_GATE(CLK_TOP_IMG1_SEL, img1_parents, 0x28, 16, 4, 23),
	/* CLK_CFG_2 */
	MUX_GATE(CLK_TOP_IPE_SEL, ipe_parents, 0x38, 0, 4, 7),
	MUX_GATE(CLK_TOP_CAM_SEL, cam_parents, 0x38, 16, 4, 23),
	/* CLK_CFG_4 */
	MUX_GATE(CLK_TOP_MFG_REF_SEL, mfg_ref_parents, 0x58, 16, 2, 23),
	MUX_GATE(CLK_TOP_MFG_PLL_SEL, mfg_pll_parents, 0x58, 18, -1, -1),
	MUX_GATE(CLK_TOP_CAMTG_SEL, camtg_parents, 0x58, 24, 3, 31),
	/* CLK_CFG_5 */
	MUX_GATE(CLK_TOP_CAMTG2_SEL, camtg2_parents, 0x68, 0, 3, 7),
	MUX_GATE(CLK_TOP_CAMTG3_SEL, camtg3_parents, 0x68, 8, 3, 15),
	MUX_GATE(CLK_TOP_CAMTG4_SEL, camtg4_parents, 0x68, 16, 3, 23),
	MUX_GATE(CLK_TOP_CAMTG5_SEL, camtg5_parents, 0x68, 24, 3, 31),
	/* CLK_CFG_6 */
	MUX_GATE(CLK_TOP_CAMTG6_SEL, camtg6_parents, 0x78, 0, 3, 7),
	MUX_GATE(CLK_TOP_UART_SEL, uart_parents, 0x78, 8, 1, 15),
	MUX_GATE(CLK_TOP_SPI_SEL, spi_parents, 0x78, 16, 3, 23),
	MUX_GATE(CLK_TOP_MSDC50_0_HCLK_SEL, msdc5hclk_parents, 0x78, 24, 2, 31),
	/* CLK_CFG_7 */
	MUX_GATE(CLK_TOP_MSDC50_0_SEL, msdc50_0_parents, 0x88, 0, 3, 7),
	MUX_GATE(CLK_TOP_MSDC30_1_SEL, msdc30_1_parents, 0x88, 8, 3, 15),
	MUX_GATE(CLK_TOP_AUDIO_SEL, audio_parents, 0x88, 24, 2, 31),
	/* CLK_CFG_8 */
	MUX_GATE(CLK_TOP_AUD_INTBUS_SEL, aud_intbus_parents, 0x98, 0, 2, 7),
	MUX_GATE(CLK_TOP_PWRAP_ULPOSC_SEL, pwrap_ulposc_parents, 0x98, 8, 3, 15),
	MUX_GATE(CLK_TOP_ATB_SEL, atb_parents, 0x98, 16, 2, 23),
	MUX_GATE(CLK_TOP_SSPM_SEL, sspm_parents, 0x98, 24, 3),
	/* CLK_CFG_9 */
	MUX_GATE(CLK_TOP_SCAM_SEL, scam_parents, 0xA8, 8, 1, 15),
	MUX_GATE(CLK_TOP_DISP_PWM_SEL, disp_pwm_parents, 0xA8, 16, 3, 23),
	MUX_GATE(CLK_TOP_USB_TOP_SEL, usb_parents, 0xA8, 24, 2, 31),
	/* CLK_CFG_10 */
	MUX_GATE(CLK_TOP_I2C_SEL, i2c_parents, 0xB8, 8, 2, 15),
	MUX_GATE(CLK_TOP_SENINF_SEL, seninf_parents, 0xB8, 16, 3, 23),
	MUX_GATE(CLK_TOP_SENINF1_SEL, seninf1_parents, 0xB8, 24, 3, 31),
	/* CLK_CFG_11 */
	MUX_GATE(CLK_TOP_SENINF2_SEL, seninf2_parents, 0xC8, 0, 3, 7),
	MUX_GATE(CLK_TOP_SENINF3_SEL, seninf3_parents, 0xC8, 8, 3, 15),
	MUX_GATE(CLK_TOP_DXCC_SEL, dxcc_parents, 0xC8, 24, 2),
	/* CLK_CFG_12 */
	MUX_GATE(CLK_TOP_AUD_ENGEN1_SEL, aud_engen1_parents, 0xD8, 0, 2, 7),
	MUX_GATE(CLK_TOP_AUD_ENGEN2_SEL, aud_engen2_parents, 0xD8, 8, 2, 15),
	MUX_GATE(CLK_TOP_AES_UFSFDE_SEL, aes_ufsfde_parents, 0xD8, 16, 3, 23),
	MUX_GATE(CLK_TOP_UFS_SEL, ufs_parents, 0xD8, 24, 3),
	/* CLK_CFG_13 */
	MUX_GATE(CLK_TOP_AUD_1_SEL, aud_1_parents, 0xE8, 0, 1, 7),
	MUX_GATE(CLK_TOP_AUD_2_SEL, aud_2_parents, 0xE8, 8, 1, 15),
	MUX_GATE(CLK_TOP_DPMAIF_MAIN_SEL, dpmaif_main_parents, 0xE8, 24, 3, 31),
	/* CLK_CFG_14 */
	MUX_GATE(CLK_TOP_VENC_SEL, venc_parents, 0xF8, 0, 4, 7),
	MUX_GATE(CLK_TOP_VDEC_SEL, vdec_parents, 0xF8, 8, 4, 15),
	MUX_GATE(CLK_TOP_CAMTM_SEL, camtm_parents, 0xF8, 16, 2, 23),
	MUX_GATE(CLK_TOP_PWM_SEL, pwm_parents, 0xF8, 24, 1, 31),
	/* CLK_CFG_15 */
	MUX_GATE(CLK_TOP_AUDIO_H_SEL, audio_h_parents, 0x0108, 0, 2, 7),
	MUX_GATE(CLK_TOP_SPMI_MST_SEL, spmi_mst_parents, 0x0108, 8, 3),
	MUX_GATE(CLK_TOP_DVFSRC_SEL, dvfsrc_parents, 0x0108, 16, 1),
	MUX_GATE(CLK_TOP_AES_MSDCFDE_SEL, aes_msdcfde_parents, 0x0108, 24, 3, 31),
	/* CLK_CFG_16 */
	MUX_GATE(CLK_TOP_MCUPM_SEL, mcupm_parents, 0x0118, 0, 2),
	MUX_GATE(CLK_TOP_DSI_OCC_SEL, dsi_occ_parents, 0x0118, 16, 2, 23),
};

static const struct mtk_clk_tree mt6789_clk_tree = {
	.xtal_rate = 26 * MHZ,
	.xtal2_rate = 26 * MHZ,
	.fdivs_offs = CLK_TOP_CLKRTC,
	.muxes_offs = CLK_TOP_AXI_SEL,
	.plls = apmixed_plls,
	.fclks = top_fixed_clks,
	.fdivs = top_fixed_divs,
	.muxes = top_muxes,
};

static const struct mtk_gate_regs infra_ao0_cg_regs = {
	.set_ofs = 0x80,
	.clr_ofs = 0x84,
	.sta_ofs = 0x90,
};

static const struct mtk_gate_regs infra_ao1_cg_regs = {
	.set_ofs = 0x88,
	.clr_ofs = 0x8C,
	.sta_ofs = 0x94,
};

static const struct mtk_gate_regs infra_ao2_cg_regs = {
	.set_ofs = 0xA4,
	.clr_ofs = 0xA8,
	.sta_ofs = 0xAC,
};

static const struct mtk_gate_regs infra_ao3_cg_regs = {
	.set_ofs = 0xC0,
	.clr_ofs = 0xC4,
	.sta_ofs = 0xC8,
};

static const struct mtk_gate_regs infra_ao4_cg_regs = {
	.set_ofs = 0xE0,
	.clr_ofs = 0xE4,
	.sta_ofs = 0xE8,
};

static const struct mtk_gate_regs infra_ao5_cg_regs = {
	.set_ofs = 0xd0,
	.clr_ofs = 0xd4,
	.sta_ofs = 0xd8,

};

#define GATE_IFRX(_id, _parent, _shift, _regs)			\
	{							\
		.id = _id,					\
		.parent = _parent,				\
		.regs = _regs,					\
		.shift = _shift,				\
		.flags = CLK_GATE_SETCLR | CLK_PARENT_TOPCKGEN,	\
	}

#define GATE_IFRAO0(_id, _parent, _shift)				\
	GATE_IFRX(_id, _parent, _shift, &infra_ao0_cg_regs)

#define GATE_IFRAO1(_id, _parent, _shift)				\
	GATE_IFRX(_id, _parent, _shift, &infra_ao1_cg_regs)

#define GATE_IFRAO2(_id, _parent, _shift)				\
	GATE_IFRX(_id, _parent, _shift, &infra_ao2_cg_regs)

#define GATE_IFRAO3(_id, _parent, _shift)				\
	GATE_IFRX(_id, _parent, _shift, &infra_ao3_cg_regs)

#define GATE_IFRAO4(_id, _parent, _shift)				\
	GATE_IFRX(_id, _parent, _shift, &infra_ao4_cg_regs)

#define GATE_IFRAO5(_id, _parent, _shift)				\
	GATE_IFRX(_id, _parent, _shift, &infra_ao5_cg_regs)

static const struct mtk_gate infra_ao_clks[] = {
	/* IFRAO0 */
	GATE_IFRAO0(CLK_IFRAO_PMIC_TMR, CLK_TOP_AXI_SEL, 0),
	GATE_IFRAO0(CLK_IFRAO_PMIC_AP, CLK_TOP_PWRAP_ULPOSC_SEL, 1),
	GATE_IFRAO0(CLK_IFRAO_GCE, CLK_TOP_AXI_SEL, 8),
	GATE_IFRAO0(CLK_IFRAO_GCE2, CLK_TOP_AXI_SEL, 9),
	GATE_IFRAO0(CLK_IFRAO_THERM, CLK_TOP_AXI_SEL, 10),
	GATE_IFRAO0(CLK_IFRAO_I2C_PSEUDO, CLK_TOP_I2C_SEL, 11),
	GATE_IFRAO0(CLK_IFRAO_APDMA_PSEUDO, CLK_TOP_AXI_SEL, 12),
	GATE_IFRAO0(CLK_IFRAO_PWM_HCLK, CLK_TOP_AXI_SEL, 15),
	GATE_IFRAO0(CLK_IFRAO_PWM1, CLK_TOP_PWM_SEL, 16),
	GATE_IFRAO0(CLK_IFRAO_PWM2,CLK_TOP_PWM_SEL, 17),
	GATE_IFRAO0(CLK_IFRAO_PWM3, CLK_TOP_PWM_SEL, 18),
	GATE_IFRAO0(CLK_IFRAO_PWM4, CLK_TOP_PWM_SEL, 19),
	GATE_IFRAO0(CLK_IFRAO_PWM, CLK_TOP_PWM_SEL , 21),
	GATE_IFRAO0(CLK_IFRAO_UART0, CLK_TOP_UART_SEL, 22),
	GATE_IFRAO0(CLK_IFRAO_UART1, CLK_TOP_UART_SEL, 23),
	GATE_IFRAO0(CLK_IFRAO_UART2, CLK_TOP_UART_SEL, 24),
	GATE_IFRAO0(CLK_IFRAO_UART3, CLK_TOP_UART_SEL, 25),
	GATE_IFRAO0(CLK_IFRAO_GCE_26M, CLK_TOP_AXI_SEL, 27),
	GATE_IFRAO0(CLK_IFRAO_BTIF, CLK_TOP_AXI_SEL, 31),
	/* IFRAO1 */
	GATE_IFRAO1(CLK_IFRAO_SPI0, CLK_TOP_SPI_SEL, 1),
	GATE_IFRAO1(CLK_IFRAO_MSDC0, CLK_TOP_AXI_SEL, 2),
	GATE_IFRAO1(CLK_IFRAO_MSDC1, CLK_TOP_AXI_SEL, 4),
	GATE_IFRAO1(CLK_IFRAO_MSDC0_SRC, CLK_TOP_MSDC50_0_SEL, 6),
	GATE_IFRAO1(CLK_IFRAO_AUXADC, CLK_TOP_CLK26M, 10),
	GATE_IFRAO1(CLK_IFRAO_CPUM, CLK_TOP_AXI_SEL, 11),
	GATE_IFRAO1(CLK_IFRAO_CCIF1_AP, CLK_TOP_AXI_SEL, 12),
	GATE_IFRAO1(CLK_IFRAO_CCIF1_MD, CLK_TOP_AXI_SEL, 13),
	GATE_IFRAO1(CLK_IFRAO_AUXADC_MD, CLK_TOP_CLK26M, 14),
	GATE_IFRAO1(CLK_IFRAO_MSDC1_SRC, CLK_TOP_MSDC30_1_SEL, 16),
	GATE_IFRAO1(CLK_IFRAO_MSDC0_AES, CLK_TOP_MSDC50_0_SEL, 17),
	GATE_IFRAO1(CLK_IFRAO_CCIF_AP, CLK_TOP_AXI_SEL, 23),
	GATE_IFRAO1(CLK_IFRAO_DEBUGSYS, CLK_TOP_AXI_SEL, 24),
	GATE_IFRAO1(CLK_IFRAO_AUDIO, CLK_TOP_AXI_SEL, 25),
	GATE_IFRAO1(CLK_IFRAO_CCIF_MD, CLK_TOP_AXI_SEL, 26),
	/* IFRAO2 */
	GATE_IFRAO2(CLK_IFRAO_SSUSB, CLK_TOP_USB_TOP_SEL, 1),
	GATE_IFRAO2(CLK_IFRAO_DISP_PWM, CLK_TOP_PWM_SEL, 2),
	GATE_IFRAO2(CLK_IFRAO_CLDMA_BCLK, CLK_TOP_AXI_SEL, 3),
	GATE_IFRAO2(CLK_IFRAO_AUDIO_26M_BCLK, CLK_TOP_CLK26M, 4),
	GATE_IFRAO2(CLK_IFRAO_SPI1, CLK_TOP_SPI_SEL, 6),
	GATE_IFRAO2(CLK_IFRAO_SPI2, CLK_TOP_SPI_SEL, 9),
	GATE_IFRAO2(CLK_IFRAO_SPI3, CLK_TOP_SPI_SEL, 10),
	GATE_IFRAO2(CLK_IFRAO_UNIPRO_SYSCLK, CLK_TOP_UFS_SEL, 11),
	GATE_IFRAO2(CLK_IFRAO_UNIPRO_TICK, CLK_TOP_CLK26M, 12),
	GATE_IFRAO2(CLK_IFRAO_UFS_SAP_BCLK, CLK_TOP_CLK26M, 13),
	GATE_IFRAO2(CLK_IFRAO_SPI4, CLK_TOP_SPI_SEL, 25),
	GATE_IFRAO2(CLK_IFRAO_SPI5, CLK_TOP_SPI_SEL, 26),
	GATE_IFRAO2(CLK_IFRAO_CQ_DMA, CLK_TOP_AXI_SEL, 27),
	GATE_IFRAO2(CLK_IFRAO_UFS, CLK_TOP_UFS_SEL, 28),
	GATE_IFRAO2(CLK_IFRAO_UFS_AES, CLK_TOP_AES_UFSFDE_SEL, 29),
	/* IFRAO3 */
	GATE_IFRAO3(CLK_IFRAO_AP_MSDC0, CLK_TOP_MSDC50_0_SEL, 7),
	GATE_IFRAO3(CLK_IFRAO_MD_MSDC0, CLK_TOP_MSDC50_0_SEL, 8),
	GATE_IFRAO3(CLK_IFRAO_CCIF5_MD, CLK_TOP_AXI_SEL, 10),
	GATE_IFRAO3(CLK_IFRAO_CCIF2_AP, CLK_TOP_AXI_SEL, 16),
	GATE_IFRAO3(CLK_IFRAO_CCIF2_MD, CLK_TOP_AXI_SEL, 17),
	GATE_IFRAO3(CLK_IFRAO_FBIST2FPC, CLK_TOP_MSDC50_0_SEL, 24),
	GATE_IFRAO3(CLK_IFRAO_DPMAIF_MAIN, CLK_TOP_DPMAIF_MAIN_SEL, 26),
	GATE_IFRAO3(CLK_IFRAO_CCIF4_AP, CLK_TOP_AXI_SEL, 28),
	GATE_IFRAO3(CLK_IFRAO_CCIF4_MD, CLK_TOP_AXI_SEL, 29),
	GATE_IFRAO3(CLK_IFRAO_SPI6_CK, CLK_TOP_SPI_SEL, 30),
	GATE_IFRAO3(CLK_IFRAO_SPI7_CK, CLK_TOP_SPI_SEL, 31),
	/* IFRAO4 */
	GATE_IFRAO4(CLK_IFRAO_66MP_BUS_MCLK_CKP, CLK_TOP_AXI_SEL, 2),
	/* IFRAO5 */
	GATE_IFRAO5(CLK_IFRAO_AP_DMA, CLK_TOP_AXI_SEL, 31),
};

static int mt6789_apmixedsys_probe(struct udevice *dev)
{
	return mtk_common_clk_init(dev, &mt6789_clk_tree);
}

static int mt6789_topckgen_probe(struct udevice *dev)
{
	return mtk_common_clk_init(dev, &mt6789_clk_tree);
}

static int mt6789-infracfg_ao_probe(struct udevice *dev)
{
	return mtk_common_clk_gate_init(dev, &mt6789_clk_tree, infra_ao_clks);
}

static const struct udevice_id mt6789_apmixed_compat[] = {
	{ .compatible = "mediatek,mt6789-apmixedsys", },
	{ }
};

static const struct udevice_id mt6789_topckgen_compat[] = {
	{ .compatible = "mediatek,mt6789-topckgen", },
	{ }
};

static const struct udevice_id mt6789_infracfg_compat[] = {
	{ .compatible = "mediatek,mt6789-infracfg_ao", },
	{ }
};

U_BOOT_DRIVER(mtk_clk_apmixedsys) = {
	.name = "mt6789-apmixedsys",
	.id = UCLASS_CLK,
	.of_match = mt6789_apmixed_compat,
	.probe = mt6789_apmixedsys_probe,
	.priv_auto = sizeof(struct mtk_clk_priv),
	.ops = &mtk_clk_apmixedsys_ops,
	.flags = DM_FLAG_PRE_RELOC,
};

U_BOOT_DRIVER(mtk_clk_topckgen) = {
	.name = "mt6789-topckgen",
	.id = UCLASS_CLK,
	.of_match = mt6789_topckgen_compat,
	.probe = mt6789_topckgen_probe,
	.priv_auto = sizeof(struct mtk_clk_priv),
	.ops = &mtk_clk_topckgen_ops,
	.flags = DM_FLAG_PRE_RELOC,
};

U_BOOT_DRIVER(mtk_clk_infracfg) = {
	.name = "mediatek,mt6789-infracfg",
	.id = UCLASS_CLK,
	.of_match = mediatek,mt6789_infracfg_compat,
	.probe = mediatek,mt6789-infracfg_probe,
	.priv_auto = sizeof(struct mtk_clk_priv),
	.ops = &mtk_clk_gate_ops,
	.flags = DM_FLAG_PRE_RELOC,
};
